options:
  OPENBW_ENABLE_UI: 1
  # For mac replace with this
  #BWAPI_CONFIG_AI__AI: BWEnv/build/BWEnv.dylib

  # Replace with your own starcraft map
  BWAPI_CONFIG_AUTO_MENU__MAP: /home/apsdehal/projects/nyu/is/gym-starcraft/micro-empty2.scm
  BWAPI_CONFIG_AI__AI: BWEnv/build/BWEnv.so
